<?php
$doctors = [
    [
        'id' => 'dr-ayushi-agarwal',
        'slug' => 'dr-ayushi-agarwal',
        'name' => 'Dr. Ayushi Agarwal',
        'specialty' => 'Interventional Cardiologist',
        'department' => 'Cardiac Sciences',
        'specialty_code' => 'cardiology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ashish-srivastava',
        'name' => 'Dr. Ashish Srivastava',
        'specialty' => 'Clinical Cardiologist',
        'department' => 'Cardiac Sciences',
        'specialty_code' => 'cardiology',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-suresh-babu',
        'name' => 'Dr. Suresh Babu',
        'specialty' => 'Senior Consultant Physician',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 39,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-sunil-kumar-sharma',
        'name' => 'Dr. Sunil Kumar Sharma',
        'specialty' => 'Senior Consultant Orthopedic',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 4,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/dr-sunil-kumar.webp',
        'image_small' => '../assets/images/doctors/small/dr-sunil-kumar.webp'
    ],
    [
        'id' => 'dr-arun-garg',
        'name' => 'Dr. Arun Garg',
        'specialty' => 'Consultant ENT Specialist',
        'department' => 'ENT',
        'specialty_code' => 'ent',
        'experience' => 30,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-divya-jyoti-sharma',
        'name' => 'Dr. Divya Jyoti Sharma',
        'specialty' => 'Neurosurgeon',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-nupur-rajoriya',
        'name' => 'Dr. Nupur Rajoriya',
        'specialty' => 'Neurologist',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 8,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-sp-sharma',
        'name' => 'Dr. S. P. Sharma',
        'specialty' => 'Sr. Consultant',
        'department' => 'Paediatric',
        'specialty_code' => 'paediatric',
        'experience' => 46,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => '../assets/images/doctors/Dr-SP-Sharma.webp',
        'image_small' => '../assets/images/doctors/small/dr-s-p-sharma.webp'
    ],
    [
        'id' => 'dr-bp-singh',
        'name' => 'Dr. B. P. Singh',
        'specialty' => 'Joint Replacement Surgeon',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 20,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-sachin-kumar',
        'name' => 'Dr. Sachin Kumar',
        'specialty' => 'Senior Consultant Orthopedic Surgeon',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 25,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-naveen-kumar',
        'name' => 'Dr. Naveen Kumar',
        'specialty' => 'Medical Gastroenterologist',
        'department' => 'Gastroenterology',
        'specialty_code' => 'gastroenterology',
        'experience' => 22,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-kamna-saxena',
        'name' => 'Dr. Kamna Saxena',
        'specialty' => 'Senior Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 32,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-manju-sinha',
        'name' => 'Dr. Manju Sinha',
        'specialty' => 'Sr. Consultant',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 45,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-bayya-sampath-akhila',
        'name' => 'Dr. Bayya Sampath Akhila',
        'specialty' => 'Consultant',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 5,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-uma-sharma',
        'name' => 'Dr. Uma Sharma',
        'specialty' => 'Consultant Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 12,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-soni-singh',
        'name' => 'Dr. Soni Singh',
        'specialty' => 'Consultant Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/Dr.-Soni-Singh.webp',
        'image_small' => '../assets/images/doctors/small/dr-soni-singh.webp'
    ],
    [
        'id' => 'dr-pallavi-panda',
        'name' => 'Dr. Pallavi Panda',
        'specialty' => 'Consultant Dentist',
        'department' => 'Dental Sciences',
        'specialty_code' => 'dental',
        'experience' => 9,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => '../assets/images/doctors/dr-pallavi-panda.webp',
        'image_small' => '../assets/images/doctors/small/dr-pallavi-panda.webp'
    ],
    [
        'id' => 'dr-anuradha',
        'name' => 'Dr. Anuradha',
        'specialty' => 'Consultant',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 7,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => '../assets/images/doctors/dr-anuradha.webp',
        'image_small' => '../assets/images/doctors/small/dr-anuradha.webp'
    ],
    [
        'id' => 'dr-harekrishna-pattra',
        'name' => 'Dr. Harekrishna Pattra',
        'specialty' => 'Consultant',
        'department' => 'General Surgery',
        'specialty_code' => 'surgery',
        'experience' => 50,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/dr-h-patra.webp',
        'image_small' => '../assets/images/doctors/small/dr-harekrishna.webp'
    ],
    [
        'id' => 'dr-rajeev-rahi',
        'name' => 'Dr. Rajeev Rahi',
        'specialty' => 'Consultant',
        'department' => 'General Surgery',
        'specialty_code' => 'surgery',
        'experience' => 23,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => '../assets/images/doctors/dr-rajiv-rahi.webp',
        'image_small' => '../assets/images/doctors/small/dr-rajeev-rahi.webp'
    ],
    [
        'id' => 'dr-vikram-singh-solanki',
        'name' => 'Dr. Vikram Singh Solanki',
        'specialty' => 'Sr. Consultant',
        'department' => 'General Surgery',
        'specialty_code' => 'surgery',
        'experience' => 41,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => '../assets/images/doctors/dr-v-s-solanki.webp',
        'image_small' => '../assets/images/doctors/small/dr-vikram-singh.webp'
    ],
    [
        'id' => 'dr-alok-krishna-shahay',
        'name' => 'Dr. Alok Krishna Shahay',
        'specialty' => 'Senior Consultant Internal Medicine',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 34,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/dr-alok-krishna.webp',
        'image_small' => '../assets/images/doctors/small/dr-alok-krishna.webp'
    ],
    [
        'id' => 'dr-prakhar-gupta',
        'name' => 'Dr. Prakhar Gupta',
        'specialty' => 'Consultant Internal Medicine',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ankur-upadhayay',
        'name' => 'Dr. Ankur Upadhayay',
        'specialty' => 'Consultant Orthopedics',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 5,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anuj-tripathi',
        'name' => 'Dr. Anuj Tripathi',
        'specialty' => 'Physician & Intensivist',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-vipin-jain',
        'name' => 'Dr. Vipin Jain',
        'specialty' => 'Consultant',
        'department' => 'Paediatrics',
        'specialty_code' => 'paediatrics',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-suresh-gupta',
        'name' => 'Dr. Suresh Gupta',
        'specialty' => 'Sr. Consultant (MD Medicine)',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => '../assets/images/doctors/dr-suresh-gupta.webp',
        'image_small' => '../assets/images/doctors/small/dr-suresh-gupta.webp'
    ],
    [
        'id' => 'dr-ranjan',
        'name' => 'Dr. Ranjan',
        'specialty' => 'Emergency Medicine / Casualty Medical Officer',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-shabeer-ahmad',
        'name' => 'Dr. Shabeer Ahmad',
        'specialty' => 'Medical Gastroenterologist',
        'department' => 'Gastroenterology',
        'specialty_code' => 'gastroenterology',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-jata-shankar-kumar',
        'name' => 'Dr. Jata Shankar Kumar',
        'specialty' => 'Consultant',
        'department' => 'Gastroenterology',
        'specialty_code' => 'gastroenterology',
        'experience' => 3,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-prasad-dandekar',
        'name' => 'Dr. Prasad Dandekar',
        'specialty' => 'Nephrologist',
        'department' => 'Renal Sciences',
        'specialty_code' => 'nephrology',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => '../assets/images/doctors/Dr-Prasad-Dandekar.webp',
        'image_small' => '../assets/images/doctors/small/dr-prasad-dandekar.webp'
    ],
    [
        'id' => 'dr-rk-saxena',
        'name' => 'Dr. R. K. Saxena',
        'specialty' => 'Senior Nephrologist',
        'department' => 'Renal Sciences',
        'specialty_code' => 'nephrology',
        'experience' => 20,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/dr-r-k-saxena.webp',
        'image_small' => '../assets/images/doctors/small/dr-r-k-saxena.webp'
    ],
    [
        'id' => 'dr-ajay-garg',
        'name' => 'Dr. Ajay Garg',
        'specialty' => 'ENT Specialist',
        'department' => 'ENT',
        'specialty_code' => 'ent',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => '../assets/images/doctors/Dr-Ajay-Garg.webp',
        'image_small' => '../assets/images/doctors/small/dr-ajay-garg.webp'
    ],
    [
        'id' => 'dr-ravi-agarwal',
        'name' => 'Dr. Ravi Agarwal',
        'specialty' => 'Dental Surgeon',
        'department' => 'Dental Sciences',
        'specialty_code' => 'dental',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-lalit-harswarup-agrawal',
        'name' => 'Dr. Lalit Harswarup Agrawal',
        'specialty' => 'Consultant',
        'department' => 'Plastic Surgeon',
        'specialty_code' => 'plastic-surgery',
        'experience' => 5,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-aditi-wadhwa',
        'name' => 'Dr. Aditi Wadhwa',
        'specialty' => 'Dermatologist',
        'department' => 'Dermatology',
        'specialty_code' => 'dermatology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ashish-kumar-shah',
        'name' => 'Dr. Ashish Kumar Shah',
        'specialty' => 'Psychiatrist',
        'department' => 'Psychiatry',
        'specialty_code' => 'psychiatry',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-nrapendra-sharma',
        'name' => 'Dr. Nrapendra Sharma',
        'specialty' => 'Consultant',
        'department' => 'Urology',
        'specialty_code' => 'urology',
        'experience' => 6,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-saurav-bhagat',
        'name' => 'Dr. Saurav Bhagat',
        'specialty' => 'Radiologist',
        'department' => 'Diagnostic Services',
        'specialty_code' => 'diagnostics',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => '../assets/images/doctors/dr-saurabh-bhagat.webp',
        'image_small' => '../assets/images/doctors/small/dr-saurabh-bhagat.webp'
    ],
    [
        'id' => 'dr-alka-kapoor',
        'name' => 'Dr. Alka Kapoor',
        'specialty' => 'Consultant',
        'department' => 'Microbiologist',
        'specialty_code' => 'diagnostics',
        'experience' => 19,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => '../assets/images/doctors/dr-alka-kapoor.webp',
        'image_small' => '../assets/images/doctors/small/dr-alka-kapoor.webp'
    ],
    [
        'id' => 'dr-ruchika-butola',
        'name' => 'Dr. Ruchika Butola',
        'specialty' => 'Consultant',
        'department' => 'Microbiologist',
        'specialty_code' => 'diagnostics',
        'experience' => 11,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anand-kumar',
        'name' => 'Dr. Anand Kumar',
        'specialty' => 'Surgical Oncologist',
        'department' => 'Oncology (Cancer Care)',
        'specialty_code' => 'oncology',
        'experience' => 18,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-priya-sharma',
        'name' => 'Dr. Priya Sharma',
        'specialty' => 'Medical Oncologist',
        'department' => 'Oncology (Cancer Care)',
        'specialty_code' => 'oncology',
        'experience' => 12,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-vikram-mehta',
        'name' => 'Dr. Vikram Mehta',
        'specialty' => 'Radiation Oncologist',
        'department' => 'Oncology (Cancer Care)',
        'specialty_code' => 'oncology',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anshu',
        'name' => 'Dr. Anshu',
        'specialty' => 'Physiotherapist',
        'department' => 'Physiotherapy',
        'specialty_code' => 'physiotherapy',
        'experience' => 5,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/dr-anshu.webp',
        'image_small' => '../assets/images/doctors/small/dr-anshu.webp'
    ],
    [
        'id' => 'dr-mitva-agarwal',
        'name' => 'Dr. Mitva Agrawal',
        'specialty' => 'Consultant ENT Specialist',
        'department' => 'ENT',
        'specialty_code' => 'ent',
        'experience' => 3.6,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/Dr-Mitva-Agarwal.webp',
        'image_small' => '../assets/images/doctors/small/dr-mitva-agarwal.webp'
    ],
    [
        'id' => 'dr-shivee-pandey',
        'name' => 'Dr. Shivee Pandey',
        'specialty' => 'Physiotherapist',
        'department' => 'Physiotherapy',
        'specialty_code' => 'physiotherapy',
        'experience' => 5,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => '../assets/images/doctors/dr-shivee-pandey.webp',
        'image_small' => '../assets/images/doctors/small/dr-shivee-pandey.webp'
    ],
    [
        'id' => 'dr-prasad-dandekar',
        'name' => 'Dr. Prasad Dandekar',
        'specialty' => 'Consultant',
        'department' => 'Nephrology',
        'specialty_code' => 'nephrology',
        'experience' => 7,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-rk-saxena',
        'name' => 'Dr. R. K. Saxena',
        'specialty' => 'Sr. Consultant',
        'department' => 'Pathology',
        'specialty_code' => 'pathology',
        'experience' => 23,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-soni-singh',
        'name' => 'Dr. Soni Singh',
        'specialty' => 'Consultant',
        'department' => 'Ophthalmology',
        'specialty_code' => 'ophthalmology',
        'experience' => 19,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-saurabh-bhagat',
        'name' => 'Dr. Saurabh Bhagat',
        'specialty' => 'Consultant',
        'department' => 'Radiology',
        'specialty_code' => 'radiology',
        'experience' => 13,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ayushi-agarwal',
        'name' => 'Dr. Ayushi Agarwal',
        'specialty' => 'Consultant',
        'department' => 'Cardiology',
        'specialty_code' => 'cardiology',
        'experience' => 9,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ashish-kumar-shah',
        'name' => 'Dr. Ashish Kumar Shah',
        'specialty' => 'Consultant',
        'department' => 'Psychiatry',
        'specialty_code' => 'psychiatry',
        'experience' => 1.5,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-uma-sharma',
        'name' => 'Dr. Uma Sharma',
        'specialty' => 'Consultant',
        'department' => 'Pulmonology',
        'specialty_code' => 'pulmonology',
        'experience' => 3,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ajay-garg',
        'name' => 'Dr. Ajay Garg',
        'specialty' => 'Consultant',
        'department' => 'Respiratory Medicine',
        'specialty_code' => 'respiratory-medicine',
        'experience' => 2,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ravi-agarwal',
        'name' => 'Dr. Ravi Agarwal',
        'specialty' => 'Sr. Consultant',
        'department' => 'Neonatology',
        'specialty_code' => 'neonatology',
        'experience' => 26,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anuj-tripathi',
        'name' => 'Dr. Anuj Tripathi',
        'specialty' => 'Consultant',
        'department' => 'Anesthesia',
        'specialty_code' => 'anesthesia',
        'experience' => 4,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-shabeer-ahmad',
        'name' => 'Dr. Shabeer Ahmad',
        'specialty' => 'Consultant',
        'department' => 'Anesthetist',
        'specialty_code' => 'anesthesia',
        'experience' => 17,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ajay-prajapati',
        'name' => 'Dr. Ajay Prajapati',
        'specialty' => 'Consultant',
        'department' => 'Neuro Surgeon',
        'specialty_code' => 'neurology',
        'experience' => 8,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-nupur-rajoriya',
        'name' => 'Dr. Nupur Rajoriya',
        'specialty' => 'Consultant',
        'department' => 'Neuro Physician',
        'specialty_code' => 'neurology',
        'experience' => 12,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ranjan',
        'name' => 'Dr. Ranjan',
        'specialty' => 'Consultant',
        'department' => 'Medical Oncology',
        'specialty_code' => 'oncology',
        'experience' => 7,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ]
];
?>
