<?php
$doctors = [
    [
        'id' => 'dr-ayushi-agarwal',
        'slug' => 'dr-ayushi-agarwal',
        'name' => 'Dr. Ayushi Agarwal',
        'specialty' => 'Interventional Cardiologist',
        'department' => 'Cardiac Sciences',
        'specialty_code' => 'cardiology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ashish-srivastava',
        'name' => 'Dr. Ashish Srivastava',
        'specialty' => 'Clinical Cardiologist',
        'department' => 'Cardiac Sciences',
        'specialty_code' => 'cardiology',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-suresh-babu',
        'name' => 'Dr. Suresh Babu',
        'specialty' => 'Senior Neurologist',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-sunil-kumar-sharma',
        'name' => 'Dr. Sunil Kumar Sharma',
        'specialty' => 'Neurologist',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-arun-garg',
        'name' => 'Dr. Arun Garg',
        'specialty' => 'Stroke Specialist',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-divya-jyoti-sharma',
        'name' => 'Dr. Divya Jyoti Sharma',
        'specialty' => 'Neurosurgeon',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-nupur-rajoriya',
        'name' => 'Dr. Nupur Rajoriya',
        'specialty' => 'Neurologist',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 8,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-sp-sharma',
        'name' => 'Dr. S. P. Sharma',
        'specialty' => 'Neurologist',
        'department' => 'Neurosciences',
        'specialty_code' => 'neurosciences',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-bp-singh',
        'name' => 'Dr. B. P. Singh',
        'specialty' => 'Joint Replacement Surgeon',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 20,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-sachin-kumar',
        'name' => 'Dr. Sachin Kumar',
        'specialty' => 'Orthopedic Surgeon',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-naveen-kumar',
        'name' => 'Dr. Naveen Kumar',
        'specialty' => 'Sports Medicine & Arthroscopy',
        'department' => 'Orthopedics',
        'specialty_code' => 'orthopedics',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-kamna-saxena',
        'name' => 'Dr. Kamna Saxena',
        'specialty' => 'Senior Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 20,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-manju-sinha',
        'name' => 'Dr. Manju Sinha',
        'specialty' => 'Obstetrician & Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 15,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-bayya-sampath-akhila',
        'name' => 'Dr. Bayya Sampath Akhila',
        'specialty' => 'Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-uma-sharma',
        'name' => 'Dr. Uma Sharma',
        'specialty' => 'Consultant Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 12,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-soni-singh',
        'name' => 'Dr. Soni Singh',
        'specialty' => 'Consultant Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-pallavi-panda',
        'name' => 'Dr. Pallavi Panda',
        'specialty' => 'Consultant Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anuradha',
        'name' => 'Dr. Anuradha',
        'specialty' => 'Consultant Gynecologist',
        'department' => 'Obstetrics & Gynecology',
        'specialty_code' => 'gynecology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-harekrishna-pattra',
        'name' => 'Dr. Harekrishna Pattra',
        'specialty' => 'General Surgeon',
        'department' => 'General & Laparoscopic Surgery',
        'specialty_code' => 'surgery',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-rajeev-rahi',
        'name' => 'Dr. Rajeev Rahi',
        'specialty' => 'General & Laparoscopic Surgeon',
        'department' => 'General & Laparoscopic Surgery',
        'specialty_code' => 'surgery',
        'experience' => 18,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-vikram-singh-solanki',
        'name' => 'Dr. Vikram Singh Solanki',
        'specialty' => 'General Surgeon',
        'department' => 'General & Laparoscopic Surgery',
        'specialty_code' => 'surgery',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-alok-krishna-shahay',
        'name' => 'Dr. Alok Krishna Shahay',
        'specialty' => 'Senior Consultant Internal Medicine',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 20,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-prakhar-gupta',
        'name' => 'Dr. Prakhar Gupta',
        'specialty' => 'Consultant Internal Medicine',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ankur-upadhayay',
        'name' => 'Dr. Ankur Upadhayay',
        'specialty' => 'Internal Medicine & Critical Care',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anuj-tripathi',
        'name' => 'Dr. Anuj Tripathi',
        'specialty' => 'Physician & Intensivist',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-vipin-jain',
        'name' => 'Dr. Vipin Jain',
        'specialty' => 'Consultant Physician',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ranjan',
        'name' => 'Dr. Ranjan',
        'specialty' => 'Emergency Medicine / Casualty Medical Officer',
        'department' => 'Internal Medicine & Critical Care',
        'specialty_code' => 'internal-medicine',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-shabeer-ahmad',
        'name' => 'Dr. Shabeer Ahmad',
        'specialty' => 'Medical Gastroenterologist',
        'department' => 'Gastroenterology',
        'specialty_code' => 'gastroenterology',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-jata-shankar-kumar',
        'name' => 'Dr. Jata Shankar Kumar',
        'specialty' => 'Surgical Gastroenterologist',
        'department' => 'Gastroenterology',
        'specialty_code' => 'gastroenterology',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-prasad-dandekar',
        'name' => 'Dr. Prasad Dandekar',
        'specialty' => 'Nephrologist',
        'department' => 'Renal Sciences',
        'specialty_code' => 'nephrology',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-rk-saxena',
        'name' => 'Dr. R. K. Saxena',
        'specialty' => 'Senior Nephrologist',
        'department' => 'Renal Sciences',
        'specialty_code' => 'nephrology',
        'experience' => 20,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ajay-garg',
        'name' => 'Dr. Ajay Garg',
        'specialty' => 'ENT Specialist',
        'department' => 'ENT',
        'specialty_code' => 'ent',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ravi-agarwal',
        'name' => 'Dr. Ravi Agarwal',
        'specialty' => 'Dental Surgeon',
        'department' => 'Dental Sciences',
        'specialty_code' => 'dental',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-lalit-harswarup-agrawal',
        'name' => 'Dr. Lalit Harswarup Agrawal',
        'specialty' => 'Plastic Surgeon',
        'department' => 'Plastic Surgery',
        'specialty_code' => 'plastic-surgery',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-aditi-wadhwa',
        'name' => 'Dr. Aditi Wadhwa',
        'specialty' => 'Dermatologist',
        'department' => 'Dermatology',
        'specialty_code' => 'dermatology',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ashish-kumar-shah',
        'name' => 'Dr. Ashish Kumar Shah',
        'specialty' => 'Psychiatrist',
        'department' => 'Psychiatry',
        'specialty_code' => 'psychiatry',
        'experience' => 12,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-nrapendra-sharma',
        'name' => 'Dr. Nrapendra Sharma',
        'specialty' => 'Psychiatrist',
        'department' => 'Psychiatry',
        'specialty_code' => 'psychiatry',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-saurav-bhagat',
        'name' => 'Dr. Saurav Bhagat',
        'specialty' => 'Radiologist',
        'department' => 'Diagnostic Services',
        'specialty_code' => 'diagnostics',
        'experience' => 10,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-alka-kapoor',
        'name' => 'Dr. Alka Kapoor',
        'specialty' => 'Pathologist',
        'department' => 'Diagnostic Services',
        'specialty_code' => 'diagnostics',
        'experience' => 15,
        'gender' => 'female',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-ruchika-butola',
        'name' => 'Dr. Ruchika Butola',
        'specialty' => 'Microbiologist',
        'department' => 'Diagnostic Services',
        'specialty_code' => 'diagnostics',
        'experience' => 10,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-anand-kumar',
        'name' => 'Dr. Anand Kumar',
        'specialty' => 'Surgical Oncologist',
        'department' => 'Oncology (Cancer Care)',
        'specialty_code' => 'oncology',
        'experience' => 18,
        'gender' => 'male',
        'availability' => 'tomorrow',
        'availability_text' => 'Available Tomorrow',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-priya-sharma',
        'name' => 'Dr. Priya Sharma',
        'specialty' => 'Medical Oncologist',
        'department' => 'Oncology (Cancer Care)',
        'specialty_code' => 'oncology',
        'experience' => 12,
        'gender' => 'female',
        'availability' => 'today',
        'availability_text' => 'Available Today',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ],
    [
        'id' => 'dr-vikram-mehta',
        'name' => 'Dr. Vikram Mehta',
        'specialty' => 'Radiation Oncologist',
        'department' => 'Oncology (Cancer Care)',
        'specialty_code' => 'oncology',
        'experience' => 15,
        'gender' => 'male',
        'availability' => 'week',
        'availability_text' => 'Available This Week',
        'image' => 'https://i.ibb.co/xnzC6pM/Untitled.webp'
    ]
];
?>
